#include "facial_data.h"
#include <QString>
#include "salt.h"
#include "indication_multiple_salts.h"

const std::array<Salt, 28> salts = {{
    {"", ""},
    {"Calcium Fluoratum", "CF"},
    {"Calcium phosphate", "CP"},
    {"Iron phosphate", "FP"},
    {"Potassium chloride", "KM"},
    {"Potassium phosphate", "KP"},
    {"Potassium sulphate", "KS"},
    {"Magnesium phosphate", "MP"},
    {"Sodium chloride", "NM"},
    {"Sodium phosphate", "NP"},
    {"Sodium sulphate", "NS"},
    {"Silica", "Sil"},
    {"Calcium sulphate", "CSulf"},
    {"Potassium arsenite", "Kali Ars"},
    {"Potassium bromide", "Kali Bro"},
    {"Potassium iodide", "Kali Lod"},
    {"Lithium chloride", "Lith Mur"},
    {"Manganese sulphate", "Manganum Sulf"},
    {"Calcium sulphide", "Calc Sulf"},
    {"Copper arsenite", "Cup Ars"},
    {"Potassium aluminium sulfuricum", "Kali Alum Sulf"},
    {"Zinc chloride", "Zinc Mur"},
    {"Calcium carbonate", "Calcium Carbanicum"},
    {"Sodium bicarbonate", "Nat Bicarb"},
    {"Arsenic iodide", "Ars Iod"},
    {"Aurum Chloratum Natronatum", "Aur Mur"},
    {"Selenium", "Sel"},
    {"Potassium dichromate", "Kali Bi"}
}};

std::vector<Indication> indications = {
    {"Fan like or dice-like wrinkles", 1},
    {"Jagged teeth", 1},
    {"Square folds around the eyes", 1},
    {"Diversified folds below the eyes", 1},
    {"Brown black coloring around the eyes", 1},
    {"Burst veins", 1},
    {"Scales in the face", 1},
    {"Cracked lips, corners of mouth, hands, fingers", 1},
    {"Periodontosis", 1},
    {"Shining skin", 1},
    {"Thin lipped mouth", 2},
    {"Shaded eyebrows", 2},
    {"Waxy skin", 2},
    {"Skin color like cheese", 2},
    {"White coating of the tongue", 2},
    {"Halitosis", 2},
    {"White noses and auricles", 2},
    {"Sweaty hair", 2},
    {"Rough voice", 2},
    {"Reddened forehead, cheeks", 3},
    {"Red, hot ears", 3},
    {"Red chin", 3},
    {"Red tongue", 3},
    {"Blue black shade in the nasal root and under the eyes", 3},
    {"Grey black colouring around the nose", 3},
    {"Pale gums", 3},
    {"Milky skin", 4},
    {"Blue white skin colour", 4},
    {"Skin like cheese", 4},
    {"Swollen lymphatic knots", 4},
    {"White coating of the tongue", 4},
    {"Mealy skin dandruff", 4},
    {"Stuck together eyes", 4},
    {"Ash-grey skin, mainly in the chin area", 5},
    {"Grey ocular part", 5},
    {"Sunken temples", 5},
    {"Absent expression", 5},
    {"Brown coating of the tongue", 5},
    {"Dry tongue", 5},
    {"Periodontosis", 5},
    {"Gum bleeding", 5},
    {"Halitosis", 5},
    {"Brown-yellow skin", 6},
    {"Dark eyelids", 6},
    {"Yellowish around the mouth", 6},
    {"Freckles", 6},
    {"Dandruff on viscous base", 6},
    {"Sticking head dandruff", 6},
    {"Yellow and slimy coating of the tongue", 6},
    {"Red, round spots on the cheeks (always or temporarily)", 7},
    {"Red spots in the neck", 7},
    {"Otherwise pale skin", 7},
    {"Convulsions of the corners of mouth", 7},
    {"Twitch of the eyelids", 7},
    {"Humid shine on the upper eyelid, like snail mucus (gelatin shine)", 8},
    {"Bright eyelids", 8},
    {"Big skin pores", 8},
    {"Bloated face", 8},
    {"Swollen, spongy cheeks", 8},
    {"Head dandruff", 8},
    {"White seclusions of the eyes", 8},
    {"Clear coating of the tongue", 8},
    {"Salivary vesicles on the edge of the tongue", 8},
    {"Skin rash in the upper forehead", 8},
    {"Itch", 8},
    {"Dry skin", 8},
    {"Greasy, dull shine on the forehead", 9},
    {"Greasy nose", 9},
    {"Big skin pores", 9},
    {"Blackhead", 9},
    {"Pimple", 9},
    {"Pale mucous membranes", 9},
    {"Hanging cheeks", 9},
    {"Double chin", 9},
    {"Tongue yellowish in the back", 9},
    {"Green-yellow complexion, especially forehead and temples", 10},
    {"Bluish redness in the nose", 10},
    {"Bluish redness in front of the ears", 10},
    {"Redness in the external corner of the eye", 10},
    {"Tongue looks dirty and greenish", 10},
    {"Shining skin, as varnished {polished shine}", 11},
    {"Waxy yellow or pale skin colour", 11},
    {"Deep-recumbent eyes", 11},
    {"Slip eyelids", 11},
    {"Laughter lines", 11},
    {"Crow´s-feet", 11},
    {"Convulsions of the eyelids", 11},
    {"Small skin pores", 11},
    {"Vertical wrinkles in front of the ears", 11},
    {"Brittle hair", 11},
    {"Dry nose", 11},
    {"Whiteness, alabaster-like skin colouring (like gypsum)", 12},
    {"Only few signs in the face", 12},
    {"Liver spots", 12},
    {"sunken cheeks", 13},
    {"dull grey color around mouth", 13},
    {"Accented prominent eyeball", 14},
    {"Acne", 14},
    {"Tired Eyes", 14},
    {"Eyebrows thin", 15},
    {"Swollen lower lip", 15},
    {"uneven wrinkle formation on neck", 15},
    {"Swelling on neck", 15},
    {"Slight turn in one eye", 15},
    {"reddish shaded eyebrows", 16},
    {"Allergies", 16},
    {"orange colored marks (upper eyelid)", 17},
    {"dark brown marks on cheek", 17},
    {"Lower eyelids dark", 17},
    {"small bag on inner canthus near eye", 18},
    {"lenticular white marks on forehead", 19},
    {"Bluish shadow underneath the eye", 19},
    {"Wrinkles, deep folds", 19},
    {"freckles", 19},
    {"“withered” eyebags", 20},
    {"Thickening of nose or ulcer", 20},
    {"dry skin lacerations at nasal wing", 20},
    {"Vertical steep wrinkles on upper lip/under lower lip", 21},
    {"White line above or/and below lips", 21},
    {"Cystic acne", 21},
    {"Cold Sores", 21},
    {"Hooded eyelids", 22},
    {"Puffy swollen face", 22},
    {"Dermatitis", 22},
    {"lack of contour of facial structures", 22},
    {"redness above the upper lip", 23},
    {"Swelling underneath the lower lip", 23},
    {"Rashes on face", 23},
    {"Blue coloration left and right to nasal wings", 24},
    {"chin and hands", 24},
    {"Bloodshot eyes", 24},
    {"Receding hairline", 25},
    {"Vertical wrinkles between eyebrow and upper lid", 25},
    {"Warts", 25},
    {"Cold sores", 26},
    {"Spots on face", 26},
    {"Jaundice", 26},
    {"Ulcers or abscesses on face", 27},
    {"Painful swallowing", 27}
};

std::vector<Indication> prominents = {
    {"Fan like or dice-like wrinkles", 1},
    {"Brown coloring around eyes", 1},
    {"Jagged teeth", 1},
    {"Waxy skin", 2},
    {"Thin lipped mouth", 2},
    {"Shaded eyebrows", 2},
    {"Redness -ears", 3},
    {"Blue black shade under eyes", 3},
    {"Pale gums", 3},
    {"White coating of tongue", 4},
    {"Milk moustache", 4},
    {"Acne roscea, spider veins", 4},
    {"Chicken skin appearance upper arms", 4},
    {"Sunken temples", 5},
    {"Raised eyebrow", 5},
    {"Ash gray appearance", 5},
    {"Pigmentation", 6},
    {"Dark eyelids", 6},
    {"Yellow around mouth", 6},
    {"Red round spots on cheeks/neck", 7},
    {"Constant red appearance", 7},
    {"Twitch of eyelids", 7},
    {"Humid shine on eyelids", 8},
    {"Large skin pores", 8},
    {"Spongy chin", 8},
    {"Pimples, blackheads", 9},
    {"Jowls", 9},
    {"Red chin", 9},
    {"Swellings, eyes, eye bag,  cheeks", 10},
    {"Bluish red coloring at nose (alcohol?liver)", 10},
    {"Yellowish sclera", 10},
    {"Vertical wrinkles in front of ears", 11},
    {"Crow´s  feet at eyes", 11},
    {"Sunken eye socket", 11},
    {"Age spots", 12},
    {"Compact wrinkles", 12},
    {"Cold white tone", 12},
    {"Sunken cheeks", 13},
    {"Dull grey color around mouth", 13},
    {"Accented prominent eyeball", 14},
    {"Acne", 14},
    {"Tired Eyes", 14},
    {"Eyebrows thin", 15},
    {"Slight turn in one eye", 15},
    {"Swollen lower lip", 15},
    {"Reddish shaded eyebrows", 16},
    {"Allergies", 16},
    {"Orange colored marks (upper eyelid)", 17},
    {"Dark brown marks on cheek", 17},
    {"Lower eyelids dark", 17},
    {"small bag on inner canthus near eye", 18},
    {"Bluish shadow underneath the eye", 19},
    {"Wrinkles, deep folds", 19},
    {"Thickening of nose or ulcer",20},
    {"dry skin lacerations at nasal wing",20},
    {"Vertical steep wrinkles on upper lip/under lower lip", 21},
    {"Cystic acne", 21},
    {"Cold Sores", 21},
    {"Hooded eyelids", 22},
    {"Puffy swollen face", 22},
    {"Dermatitis", 22},
    {"redness above the upper lip", 23},
    {"Swelling underneath the lower lip", 23},
    {"Rashes on face", 23},
    {"Blue coloration left and right to nasal wings", 24},
    {"Bloodshot eyes", 24},
    {"Receding hairline", 25},
    {"Vertical wrinkles between eyebrow and upper lid", 25},
    {"Warts", 25},
    {"Cold sores", 26},
    {"Spots on face", 26},
    {"Jaundice", 26},
    {"Ulcers or abscesses on face", 27},
    {"Painful swallowing", 27}

};

std::vector<Indication_Multiple_Salts> prominents_multiple = {
    {"Fan like or dice-like wrinkles", {1}},
    {"Brown coloring around eyes", {1}},
    {"Jagged teeth", {1}},
    {"Waxy skin", {2}},
    {"Thin lipped mouth", {2}},
    {"Shaded eyebrows", {2}},
    {"Redness -ears", {3}},
    {"Blue black shade under eyes", {3}},
    {"Pale gums", {3}},
    {"White coating of tongue", {2, 4}},
    {"Milk moustache", {4}},
    {"Acne roscea, spider veins", {4}},
    {"Chicken skin appearance upper arms", {4}},
    {"Sunken temples", {5}},
    {"Raised eyebrow", {5}},
    {"Ash gray appearance", {5}},
    {"Pigmentation", {6, 12, 19, 21, 26}},
    {"Dark eyelids", {6}},
    {"Yellow around mouth", {6}},
    {"Red round spots on cheeks/neck", {7}},
    {"Constant red appearance", {7}},
    {"Twitch of eyelids", {7}},
    {"Humid shine on eyelids", {8}},
    {"Large skin pores", {8, 9}},
    {"Spongy chin", {8}},
    {"Pimples, blackheads", {9}},
    {"Jowls", {9}},
    {"Red chin", {3, 9}},
    {"Swellings, eyes, eye bag,  cheeks", {10}},
    {"Bluish red coloring at nose (alcohol?liver)", {10}},
    {"Yellowish sclera", {10}},
    {"Vertical wrinkles in front of ears", {11}},
    {"Crow´s  feet at eyes", {11}},
    {"Sunken eye socket", {11}},
    {"Age spots", {6, 12, 19, 21, 26}},
    {"Compact wrinkles", {12}},
    {"Cold white tone", {12}},
    {"Sunken cheeks", {13}},
    {"Dull grey color around mouth", {13}},
    {"Accented prominent eyeball", {14}},
    {"Acne", {14}},
    {"Tired Eyes", {14}},
    {"Eyebrows thin", {15}},
    {"Slight turn in one eye", {15}},
    {"Swollen lower lip", {15}},
    {"Reddish shaded eyebrows", {16}},
    {"Allergies", {16}},
    {"Orange colored marks (upper eyelid)", {17}},
    {"Dark brown marks on cheek", {17}},
    {"Lower eyelids dark", {17}},
    {"small bag on inner canthus near eye", {18}},
    {"Bluish shadow underneath the eye", {19}},
    {"Wrinkles, deep folds", {19}},
    {"Thickening of nose or ulcer", {20}},
    {"dry skin lacerations at nasal wing", {20}},
    {"Vertical steep wrinkles on upper lip/under lower lip", {21}},
    {"Cystic acne", {21}},
    {"Cold Sores", {21, 26}},
    {"Hooded eyelids", {22}},
    {"Puffy swollen face", {22}},
    {"Dermatitis", {22}},
    {"redness above the upper lip", {23}},
    {"Swelling underneath the lower lip", {23}},
    {"Rashes on face", {23}},
    {"Blue coloration left and right to nasal wings", {24}},
    {"Bloodshot eyes", {24}},
    {"Receding hairline", {25}},
    {"Vertical wrinkles between eyebrow and upper lid", {25}},
    {"Warts", {25}},
    {"Spots on face", {6, 12, 19, 21, 26}},
    {"Jaundice", {26}},
    {"Ulcers or abscesses on face", {27}},
    {"Painful swallowing", {27}}

};
